lint-stage set

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -6,10 +6,10 @@ yarn test
 
 echo 'Styling ,testing and building project before committing.'
 
-#  yarn lint-staged || (
-#      echo 'Failed lint-staged check. Make the required changes listed above, add changes and try to commit again.'
-#      false;
+ yarn lint-staged || (
+     echo 'Failed lint-staged check. Make the required changes listed above, add changes and try to commit again.'
+     false;
 
-#  )
+ )
 
 echo 'Code styling check pass.Trying to build now.'
